name: Upload DLL
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload DLL
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Upload assets
        uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7
        with:
          files: |
            ./dotnet-4.8/PercyTosca_4_8.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
